//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hallo.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack request can not have a response.
        /// </summary>
        internal static string AckRequestCanNotHaveAResponse {
            get {
                return ResourceManager.GetString("AckRequestCanNotHaveAResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch parameter can not be null.
        /// </summary>
        internal static string BranchParameterCanNotBeNull {
            get {
                return ResourceManager.GetString("BranchParameterCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find name for type &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotFindNameForTypeFormatString {
            get {
                return ResourceManager.GetString("CanNotFindNameForTypeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find type for name &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotFindTypeForNameFormatString {
            get {
                return ResourceManager.GetString("CanNotFindTypeForNameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a parser for header with name: {0}.
        /// </summary>
        internal static string CouldNotFindHeaderParserFormatString {
            get {
                return ResourceManager.GetString("CouldNotFindHeaderParserFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} for header &apos;{1}&apos; can not be longer then {2} characters.
        /// </summary>
        internal static string HeaderFieldCanNotBeLongerThen {
            get {
                return ResourceManager.GetString("HeaderFieldCanNotBeLongerThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value for header &apos;{0}&apos; can not be longer then {1} characters.
        /// </summary>
        internal static string HeaderValueCanNotBeLongerThen {
            get {
                return ResourceManager.GetString("HeaderValueCanNotBeLongerThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Body Lenght.
        /// </summary>
        internal static string InvalidBodyLenght {
            get {
                return ResourceManager.GetString("InvalidBodyLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FirstLine Format.
        /// </summary>
        internal static string InvalidFirstLineFormat {
            get {
                return ResourceManager.GetString("InvalidFirstLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidFormat.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidHeaderName.
        /// </summary>
        internal static string InvalidHeaderName {
            get {
                return ResourceManager.GetString("InvalidHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidRequestLineFormat.
        /// </summary>
        internal static string InvalidRequestLineFormat {
            get {
                return ResourceManager.GetString("InvalidRequestLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSdpOriginLineFormat.
        /// </summary>
        internal static string InvalidSdpOriginLineFormat {
            get {
                return ResourceManager.GetString("InvalidSdpOriginLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSipVersion.
        /// </summary>
        internal static string InvalidSipVersion {
            get {
                return ResourceManager.GetString("InvalidSipVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidStatusLineFormat.
        /// </summary>
        internal static string InvalidStatusLineFormat {
            get {
                return ResourceManager.GetString("InvalidStatusLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Transport.
        /// </summary>
        internal static string InvalidTransport {
            get {
                return ResourceManager.GetString("InvalidTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedHostsAreNotSupported.
        /// </summary>
        internal static string NamedHostsAreNotSupported {
            get {
                return ResourceManager.GetString("NamedHostsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullString.
        /// </summary>
        internal static string NullString {
            get {
                return ResourceManager.GetString("NullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single valued header can be added.
        /// </summary>
        internal static string OnlySingleValuedHeaderCanBeAdded {
            get {
                return ResourceManager.GetString("OnlySingleValuedHeaderCanBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sip method &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string SipMethodNotSupprted {
            get {
                return ResourceManager.GetString("SipMethodNotSupprted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrictRouting is not supported. Only &apos;Loose routing&apos; is allowed..
        /// </summary>
        internal static string StrictRoutingIsNotSupported {
            get {
                return ResourceManager.GetString("StrictRoutingIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header to set can not be a headerlist.
        /// </summary>
        internal static string TheHeaderToSetCanNotBeHeaderList {
            get {
                return ResourceManager.GetString("TheHeaderToSetCanNotBeHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownHeader.
        /// </summary>
        internal static string UnknownHeader {
            get {
                return ResourceManager.GetString("UnknownHeader", resourceCulture);
            }
        }
    }
}
